# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: es-MX

# Site title
title: "aceron[\"blog\"]"

# A description of your site for meta tag, search engine results.
description: "Blog personal para compartir ideas, quejas y algunos tutoriales"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://a-ceron.github.io/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Inicio
    url: /
  - text: Acerca del sitio
    url: /about/
  - text: Acerca del autor
    url: /about-aceron/
  - text: Categorias
    url: /tags/
  # - text: Download
  #   url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2c343c'

# Site footer
footer:
  content: "&copy; Todo el contenido presente son puras experiencias o contenido aprendido en mi vida. Nada de lo aquí dicho es la palabra final, siempre puede haber un cambio \n Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
# Número de post por pagina
paginate: 5
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
